### ISSUE TITLE
Arch Linux 5.7.12 no bluetooth devices

### ISSUE THREAD

**Issue by miklosakos** [Coutj/Bluetooth_project#1]
Whenever I run the python script, click load (made sure to disconnect from my headphones) nothing happens just the Bluetooth logo blinks.
Python version: 3.8.5
pybluez version: 0.23
Console output:
```
[miklos_akos@FURSTATION Bluetooth_project-master]$ python3 main.py 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/miklos_akos/Bluetooth_project-master/external_threads.py", line 9, in get_headsets_devices
    blueClass.get_bluetooth_devices()
  File "/home/miklos_akos/Bluetooth_project-master/blueP.py", line 45, in get_bluetooth_devices
    bus = dbus.SystemBus()
AttributeError: module 'dbus' has no attribute 'SystemBus'
```

**Comment by Coutj** [comment]
I'm running this app with the following configuration:

Arch 5.7.12
python 3.8.5
pybluez 0.23.

I think that this problem is related with this question on [stack overflow](https://stackoverflow.com/questions/3293172/python-dbus-problem ). 

if I run the next commands I have this exactly output:

```
$python
Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbus
>>> print (dbus.__file__)
/usr/lib/python3.8/site-packages/dbus/__init__.py
```

Could you please reproduce this steps?

I didn't get when you said "made sure to disconnect from my headphones". You have to keep the headphone connected with your computer
